- name : Configure Docker on EC2 Instances
  hosts : test-server
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root

  - name: stop container
    command: sudo docker stop insure-me
    
  - name: remove container
    command: sudo docker rm insure-me

  - name: Deploy Docker Container
    command: sudo docker run -itd -p 8082:8081 --name insure-me sailanadh123/insure-me:1.0
